{% set version = "0.7.0" %}

package:
  name: nbgitpuller
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nbgitpuller/nbgitpuller-{{ version }}.tar.gz
  sha256: 9be155973341dc7fb6259103a71c971d33ff572d4a1078ed2eadc1ee83d17b4c

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - gitpuller = nbgitpuller.pull:main

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - notebook >=5.5.0
    - tornado

test:
  imports:
    - nbgitpuller
  commands:
    - gitpuller --help

about:
  home: https://github.com/data-8/nbgitpuller
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Notebook Extension to do one-way synchronization of git repositories"

extra:
  recipe-maintainers:
    - ocefpaf
